version: "3.9"

services:
  grademed:
    container_name: grademed
    build: .
    restart: unless-stopped

    expose:
      - "80"

    networks:
      - npm_default

networks:
  npm_default:
    external: true
