version: "3.9"

services:
  grademed:
    container_name: grademed
    image: ghcr.io/eduardoazm/grademed:${APP_VERSION:-latest}
    restart: unless-stopped

    expose:
      - "80"

    networks:
      - npm_default
      - network_proxy

networks:
  npm_default:
    external: true
  network_proxy:
    external: true
